version: '3.8'

services:
  # Frontend
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    networks:
      - abrnoc-network

  # Backend
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=your-development-jwt-secret
      - DATABASE_URL=your-development-database-url
    networks:
      - abrnoc-network

  # Optional: Add a database service if needed
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: abrnoc
  #     POSTGRES_USER: abrnoc
  #     POSTGRES_PASSWORD: abrnoc
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - abrnoc-network

networks:
  abrnoc-network:
    driver: bridge

# volumes:
#   postgres_data: 