apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: abrnoc
data:
  NODE_ENV: "production"
  PORT: "3000"
  # Add other configuration variables as needed
  # JWT_SECRET: "your-jwt-secret"
  # DATABASE_URL: "your-database-url" 