apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: abrnoc
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  # echo -n "your-jwt-secret" | base64
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0
  # echo -n "your-database-url" | base64
  DATABASE_URL: eW91ci1kYXRhYmFzZS11cmw=
stringData:
  # You can also use stringData for non-base64 values
  # JWT_SECRET: "your-jwt-secret"
  # DATABASE_URL: "your-database-url" 